// ============================================================================
//  Compile database synthesis (Tier 2 / clangd, I.4).
//
//  Fixture shapes are copied from gs_play's measured reply: GS_AudioPro.API has a
//  unity-blob group plus a vendored-SoLoud group with extra warnings; four
//  launchers share one .cpp; unity blobs live under the build dir and are NOT
//  flagged isGenerated by CMake.
// ============================================================================

import * as assert from "assert";
import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import {
  buildCompileDatabase,
  groupIndexForSource,
  isOtherPlatformPath,
  listFrameworkSources,
  remapFlagTokens,
  splitFlags,
} from "../intellisense/compileDb";
import { normalizePath } from "../intellisense/paths";
import { CommandGroup, CommandReply, CommandTarget, extractForcedIncludes, extractFragmentIncludes } from "../intellisense/fileApi";
import { RootMapping } from "../intellisense/remap";

const BUILD = "D:/OffLocalDev/gs_play/build/windows";
const SOURCE = "D:/OffLocalDev/gs_play";
const CL = "C:/MSVC/bin/Hostx64/x64/cl.exe";

function group(overrides: Partial<CommandGroup>): CommandGroup {
  return { language: "CXX", fragments: [], includes: [], defines: [], sourceIndexes: [], ...overrides };
}
/** A hand-built target, with `compile` merged from its groups the way parseTarget merges real ones —
 *  including `-external:I` fragment paths as system includes, using the real extractors. */
function target(spec: Omit<CommandTarget, "compile">): CommandTarget {
  const fragments = (g: CommandGroup) => g.fragments.map((fragment) => ({ fragment }));
  return {
    ...spec,
    compile: {
      includes: spec.groups.flatMap((g) => [
        ...g.includes,
        ...extractFragmentIncludes(fragments(g)).map((p) => ({ path: p, isSystem: true })),
      ]),
      defines: spec.groups.flatMap((g) => g.defines),
      forcedIncludes: spec.groups.flatMap((g) => extractForcedIncludes(fragments(g))),
      standard: "20",
    },
  };
}
function reply(targets: CommandTarget[]): CommandReply {
  return { config: "profile", sourceDir: SOURCE, buildDir: BUILD, compilerPath: CL, targets };
}

// ---- Tokens ------------------------------------------------------------------
suite("compileDb.splitFlags", () => {
  test("splits the big MSVC flags fragment on whitespace (leading space included, as CMake emits it)", () => {
    assert.deepStrictEqual(splitFlags(" /Gd /MP /nologo  /W4 /permissive- /Zc:preprocessor"), [
      "/Gd", "/MP", "/nologo", "/W4", "/permissive-", "/Zc:preprocessor",
    ]);
  });

  test("double quotes group a token containing spaces and are dropped", () => {
    assert.deepStrictEqual(splitFlags('/FI"C:/Program Files/X/Compat.h" /W4'), ["/FIC:/Program Files/X/Compat.h", "/W4"]);
  });

  test("empty fragment → no tokens", () => {
    assert.deepStrictEqual(splitFlags("   "), []);
  });
});

suite("compileDb.remapFlagTokens", () => {
  const mappings: RootMapping[] = [{ fromRoot: "D:/GS_Sys/Engines/GS_Play_Engine", toRef: "D:/OffLocalDev/o3de_sourcedev" }];

  test("remaps the forced include, external includes and plain includes into the source engine", () => {
    assert.deepStrictEqual(
      remapFlagTokens(
        [
          "/FID:\\GS_Sys\\Engines\\GS_Play_Engine\\Code\\Framework\\AzCore\\Platform\\Common\\VSCompat.h",
          "-external:ID:/GS_Sys/Engines/GS_Play_Engine/Include/recastnavigation",
          "/ID:/GS_Sys/Engines/GS_Play_Engine/Code/Framework/AzCore",
        ],
        mappings,
      ),
      [
        "/FID:/OffLocalDev/o3de_sourcedev/Code/Framework/AzCore/Platform/Common/VSCompat.h",
        "-external:ID:/OffLocalDev/o3de_sourcedev/Include/recastnavigation",
        "/ID:/OffLocalDev/o3de_sourcedev/Code/Framework/AzCore",
      ],
    );
  });

  test("a detached value (`/I path`) is remapped as the next token", () => {
    assert.deepStrictEqual(remapFlagTokens(["/I", "D:/GS_Sys/Engines/GS_Play_Engine/Code"], mappings), [
      "/I",
      "D:/OffLocalDev/o3de_sourcedev/Code",
    ]);
  });

  test("look-alike switches are left alone", () => {
    const tokens = ["/external:W0", "/experimental:external", "/Fi", "/interface", "/FS", "-std:c++20"];
    assert.deepStrictEqual(remapFlagTokens(tokens, mappings), tokens);
  });
});

// ---- Group selection ---------------------------------------------------------
suite("compileDb.groupIndexForSource", () => {
  // GS_AudioPro.API, as measured: group 0 compiles the unity blobs, group 1 the vendored SoLoud sources.
  const audioProApi = target({
    name: "GS_AudioPro.API",
    groups: [
      group({ sourceIndexes: [0], fragments: ["/W4"] }),
      group({ sourceIndexes: [1], fragments: ["/W4", "/wd4100 /wd4996"] }),
    ],
    sources: [
      { path: `${BUILD}/External/GS_AudioPro/Code/CMakeFiles/GS_AudioPro.API.dir/Unity/unity_7_cxx.cxx`, groupIndex: 0 },
      { path: "D:/OffLocalDev/gs_play_gems/gs_audiopro/Code/Source/SoLoud/src/core/soloud.cpp", groupIndex: 1 },
      { path: "D:/OffLocalDev/gs_play_gems/gs_audiopro/Code/Source/AudioProSystem.cpp" }, // unity-batched: no index
    ],
  });

  test("a source with its own group index uses it", () => {
    assert.strictEqual(groupIndexForSource(audioProApi, 1, reply([audioProApi])), 1);
  });

  test("a unity-batched source takes the group that compiles the build's unity blobs", () => {
    assert.strictEqual(groupIndexForSource(audioProApi, 2, reply([audioProApi])), 0);
  });

  test("no blob group → the first group of the file's language", () => {
    const plain = target({ name: "T", groups: [group({ sourceIndexes: [] })], sources: [{ path: "D:/g/a.cpp" }] });
    assert.strictEqual(groupIndexForSource(plain, 0, reply([plain])), 0);
  });
});

// ---- Building the database ---------------------------------------------------
suite("compileDb.buildCompileDatabase", () => {
  const gsCore = target({
    name: "GS_Core",
    groups: [
      group({
        sourceIndexes: [0],
        defines: ["AZ_PROFILE_BUILD", "GS_Core_EXPORTS", 'LY_CMAKE_TARGET="GS_Core"'],
        includes: [
          { path: "D:/OffLocalDev/gs_play_gems/gs_core/Code/Include" },
          { path: "D:/GS_Sys/Engines/GS_Play_Engine/Code/Framework/AzCore", isSystem: true },
        ],
        fragments: [" /W4 /permissive- /FID:\\GS_Sys\\Engines\\GS_Play_Engine\\Compat\\VSCompat.h", "/external:W0"],
      }),
    ],
    sources: [
      { path: `${BUILD}/External/GS_Core/Code/CMakeFiles/GS_Core.dir/Unity/unity_0_cxx.cxx`, groupIndex: 0 },
      { path: "D:/OffLocalDev/gs_play_gems/gs_core/Code/Source/CoreSystem.cpp" },
      { path: "D:/OffLocalDev/gs_play_gems/gs_core/Code/Include/GS_Core/CoreBus.h" },
      { path: `${BUILD}/Azcg/Generated/GS_Core/Autogen.cpp`, groupIndex: 0 },
      { path: "D:/OffLocalDev/gs_play_gems/gs_core/Code/gs_core_files.cmake" },
    ],
  });
  const sourceEngineHas = new Set(["D:/OffLocalDev/o3de_sourcedev/Code/Framework/AzCore", "D:/OffLocalDev/o3de_sourcedev/Compat/VSCompat.h"]);
  const mappings: RootMapping[] = [
    {
      fromRoot: "D:/GS_Sys/Engines/GS_Play_Engine",
      toRef: "D:/OffLocalDev/o3de_sourcedev",
      verifyBase: "D:/OffLocalDev/o3de_sourcedev",
      exists: (p) => sourceEngineHas.has(p.split("\\").join("/")),
    },
  ];

  test("one entry per real compilable source — no unity blobs, no generated code, no headers or cmake", () => {
    const commands = buildCompileDatabase(reply([gsCore]), mappings);
    assert.deepStrictEqual(commands.map((c) => c.file), ["D:/OffLocalDev/gs_play_gems/gs_core/Code/Source/CoreSystem.cpp"]);
  });

  test("argv: compiler, defines, includes (system → /external:I), flags, /TP, then the file", () => {
    const [command] = buildCompileDatabase(reply([gsCore]), mappings);
    assert.strictEqual(command.directory, BUILD);
    assert.deepStrictEqual(command.arguments, [
      CL,
      "/DAZ_PROFILE_BUILD",
      "/DGS_Core_EXPORTS",
      '/DLY_CMAKE_TARGET="GS_Core"', // quotes kept literally: the macro's value IS a string
      "/ID:/OffLocalDev/gs_play_gems/gs_core/Code/Include",
      "/external:ID:/OffLocalDev/o3de_sourcedev/Code/Framework/AzCore", // remapped into the source engine
      "/W4",
      "/permissive-",
      "/FID:/OffLocalDev/o3de_sourcedev/Compat/VSCompat.h", // forced include remapped too
      "/external:W0",
      "/TP",
      "D:/OffLocalDev/gs_play_gems/gs_core/Code/Source/CoreSystem.cpp",
    ]);
  });

  test("an engine path the source engine lacks keeps its build path (verifyBase fallback)", () => {
    const withRecast = target({
      name: gsCore.name,
      sources: gsCore.sources,
      groups: [group({ ...gsCore.groups[0], includes: [{ path: "D:/GS_Sys/Engines/GS_Play_Engine/include/miniaudio", isSystem: true }] })],
    });
    const [command] = buildCompileDatabase(reply([withRecast]), mappings);
    assert.ok(command.arguments.includes("/external:ID:/GS_Sys/Engines/GS_Play_Engine/include/miniaudio"));
  });

  test("a file several launchers compile gets ONE entry with only the defines they agree on", () => {
    const launcher = (name: string, extra: string[]): CommandTarget =>
      target({
        name,
        groups: [group({ sourceIndexes: [], defines: ["AZ_PROFILE_BUILD", ...extra] })],
        sources: [{ path: "D:/OffLocalDev/gs_play/Launcher/LauncherProject.cpp" }],
      });
    const commands = buildCompileDatabase(
      reply([
        launcher("GS_Play.GameLauncher", ['LY_CMAKE_TARGET="GS_Play_GameLauncher"']),
        launcher("GS_Play.HeadlessServerLauncher", ['LY_CMAKE_TARGET="GS_Play_HeadlessServerLauncher"', "O3DE_HEADLESS_SERVER=1"]),
      ]),
      [],
    );
    assert.strictEqual(commands.length, 1);
    const defines = commands[0].arguments.filter((a) => a.startsWith("/D"));
    // LY_CMAKE_TARGET is defined by every owner (with different values) → kept once; the real
    // LauncherProject.cpp `#error`s without it. O3DE_HEADLESS_SERVER is one owner's only → dropped.
    assert.deepStrictEqual(defines, ["/DAZ_PROFILE_BUILD", '/DLY_CMAKE_TARGET="GS_Play_GameLauncher"']);
  });

  test("output is sorted by file, so regeneration is byte-stable", () => {
    const two = target({
      name: "T",
      groups: [group({})],
      sources: [{ path: "D:/g/zeta.cpp" }, { path: "D:/g/alpha.cpp" }],
    });
    assert.deepStrictEqual(buildCompileDatabase(reply([two]), []).map((c) => c.file), ["D:/g/alpha.cpp", "D:/g/zeta.cpp"]);
  });

  test("relative source paths resolve against the source dir", () => {
    const rel = target({ name: "P", groups: [group({})], sources: [{ path: "Gem/Source/GS_PlayModule.cpp" }] });
    assert.strictEqual(buildCompileDatabase(reply([rel]), [])[0].file, "D:/OffLocalDev/gs_play/Gem/Source/GS_PlayModule.cpp");
  });

  test("a target listing the same file twice still yields one entry", () => {
    const dup = target({ name: "D", groups: [group({})], sources: [{ path: "D:/g/a.cpp" }, { path: "D:/g/a.cpp" }] });
    assert.strictEqual(buildCompileDatabase(reply([dup]), []).length, 1);
  });
});

// ---- Engine source entries (redirected projects, Framework scope) ------------
suite("compileDb engine source entries", () => {
  const SDK = "D:/GS_Sys/Engines/GS_Play_Engine";
  const SRC = "D:/OffLocalDev/o3de_sourcedev";
  const mappings: RootMapping[] = [{ fromRoot: SDK, toRef: SRC }];
  // A runtime gem and an editor gem, as in gs_play: the editor one brings Qt/editor include dirs.
  const runtime = target({
    name: "GS_Core",
    groups: [
      group({
        sourceIndexes: [0],
        defines: ["AZ_PROFILE_BUILD", "GS_Core_EXPORTS"],
        includes: [{ path: `${SDK}/Code/Framework/AzCore`, isSystem: true }],
        fragments: [` /W4 /WX /permissive- /FI${SDK}/Compat/VSCompat.h`, "-external:IC:/3rdParty/RapidJSON/include"],
      }),
    ],
    sources: [{ path: "D:/OffLocalDev/gs_play_gems/gs_core/Code/Source/CoreSystem.cpp" }],
  });
  const editor = target({
    name: "GS_Core.Editor",
    groups: [
      group({
        sourceIndexes: [0],
        defines: ["AZ_PROFILE_BUILD", "QT_CORE_LIB"],
        includes: [{ path: `${SDK}/Code/Framework/AzCore`, isSystem: true }, { path: "C:/3rdParty/Qt/include", isSystem: true }],
        fragments: [` /W4 /WX /permissive- /FI${SDK}/Compat/VSCompat.h`],
      }),
    ],
    sources: [{ path: "D:/OffLocalDev/gs_play_gems/gs_core/Code/Source/Tools/CoreEditor.cpp" }],
  });
  const ENGINE_FILE = `${SRC}/Code/Framework/AzToolsFramework/AzToolsFramework/ToolsComponents/TransformComponent.cpp`;
  const engineEntry = () =>
    buildCompileDatabase(reply([runtime, editor]), mappings, [ENGINE_FILE]).find((c) => c.file === ENGINE_FILE)!;

  test("no engine sources given → exactly the project database (unchanged behaviour)", () => {
    assert.strictEqual(buildCompileDatabase(reply([runtime, editor]), mappings).length, 2);
  });

  test("an engine file gets an entry, sorted in with the project's", () => {
    const files = buildCompileDatabase(reply([runtime, editor]), mappings, [ENGINE_FILE]).map((c) => c.file);
    assert.deepStrictEqual(files, [...files].sort());
    assert.ok(files.includes(ENGINE_FILE));
  });

  test("/WX is dropped — a consumer sees engine exports as dllimport, and /WX turned those warnings into a failed parse", () => {
    assert.ok(!engineEntry().arguments.includes("/WX"));
    assert.ok(engineEntry().arguments.includes("/W4") && engineEntry().arguments.includes("/permissive-"), "other switches stay");
  });

  test("includes are the UNION across targets — editor engine code needs the editor gem's Qt dirs", () => {
    assert.ok(engineEntry().arguments.includes("/external:IC:/3rdParty/Qt/include"));
    assert.ok(engineEntry().arguments.includes(`/external:I${SRC}/Code/Framework/AzCore`), "engine include redirected");
    assert.ok(engineEntry().arguments.includes("/external:IC:/3rdParty/RapidJSON/include"), "fragment -external:I carried via the union");
  });

  test("defines are the AGREED set — no one gem's export or Qt flag leaks into engine code", () => {
    const defines = engineEntry().arguments.filter((a) => a.startsWith("/D"));
    assert.deepStrictEqual(defines, ["/DAZ_PROFILE_BUILD"]);
  });

  test("include switches are not duplicated from the flags; the forced include stays, redirected", () => {
    const args = engineEntry().arguments;
    assert.strictEqual(args.filter((a) => a === "/external:IC:/3rdParty/RapidJSON/include").length, 1);
    assert.ok(args.includes(`/FI${SRC}/Compat/VSCompat.h`));
    assert.strictEqual(args[args.length - 2], "/TP");
  });

  test("a project's real entry for the same file always wins over an engine entry", () => {
    const projectFile = "D:/OffLocalDev/gs_play_gems/gs_core/Code/Source/CoreSystem.cpp";
    const commands = buildCompileDatabase(reply([runtime, editor]), mappings, [projectFile]);
    const entries = commands.filter((c) => c.file === projectFile);
    assert.strictEqual(entries.length, 1);
    assert.ok(entries[0].arguments.includes("/WX"), "it's the project's own command, /WX and all");
  });
});

suite("compileDb.listFrameworkSources", () => {
  let root: string;
  const touch = (rel: string) => {
    const file = path.join(root, rel);
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, "");
  };
  setup(() => {
    root = fs.mkdtempSync(path.join(os.tmpdir(), "o3de-framework-"));
    touch("Code/Framework/AzCore/AzCore/Component/Component.cpp");
    touch("Code/Framework/AzCore/AzCore/Component/Component.h"); // not a source
    touch("Code/Framework/AzCore/Platform/Windows/AzCore/IO/SystemFile_Windows.cpp");
    touch("Code/Framework/AzCore/Platform/Linux/AzCore/IO/SystemFile_Linux.cpp");
    touch("Code/Framework/AzCore/Tests/ComponentTests.cpp");
    touch("Code/Framework/AzManipulatorTestFramework/Source/Viewport.cpp");
  });
  teardown(() => fs.rmSync(root, { recursive: true, force: true }));

  const rel = (files: string[]) => files.map((f) => f.slice(normalizePath(root).length + 1));

  test("sources for this platform only — no headers, tests or other platforms' PAL folders", () => {
    assert.deepStrictEqual(rel(listFrameworkSources(root, "win32")), [
      "Code/Framework/AzCore/AzCore/Component/Component.cpp",
      "Code/Framework/AzCore/Platform/Windows/AzCore/IO/SystemFile_Windows.cpp",
      "Code/Framework/AzManipulatorTestFramework/Source/Viewport.cpp",
    ]);
  });

  test("with include paths, a module the project can't #include is not listed", () => {
    const includes = [`${normalizePath(root)}/Code/Framework/AzCore`, `${normalizePath(root)}/Code/Framework/AzCore/Platform/Windows`];
    assert.deepStrictEqual(rel(listFrameworkSources(root, "win32", includes)), [
      "Code/Framework/AzCore/AzCore/Component/Component.cpp",
      "Code/Framework/AzCore/Platform/Windows/AzCore/IO/SystemFile_Windows.cpp",
    ]);
  });

  test("a source engine without Code/Framework → nothing, no crash", () => {
    assert.deepStrictEqual(listFrameworkSources(path.join(root, "missing"), "win32"), []);
  });
});

suite("compileDb.isOtherPlatformPath", () => {
  const F = "D:/Src/Code/Framework/AzCore/AzCore";
  test("Windows skips other platforms' PAL folders", () => {
    for (const p of ["Platform/Linux", "Platform/Android", "Platform/Mac", "Platform/iOS", "Platform/Emscripten", "Platform/Common/UnixLike", "Platform/Common/Apple", "Platform/Common/Wayland", "Platform/Common/Xcb"]) {
      assert.strictEqual(isOtherPlatformPath(`${F}/${p}/X.cpp`, "win32"), true, p);
    }
  });

  test("Windows keeps its own and the shared fallbacks", () => {
    for (const p of ["Platform/Windows", "Platform/Common/WinAPI", "Platform/Common/Default", "Platform/Common/Unimplemented", "Component"]) {
      assert.strictEqual(isOtherPlatformPath(`${F}/${p}/X.cpp`, "win32"), false, p);
    }
  });

  test("Linux skips Windows and WinAPI instead", () => {
    assert.strictEqual(isOtherPlatformPath(`${F}/Platform/Windows/X.cpp`, "linux"), true);
    assert.strictEqual(isOtherPlatformPath(`${F}/Platform/Common/WinAPI/X.cpp`, "linux"), true);
    assert.strictEqual(isOtherPlatformPath(`${F}/Platform/Linux/X.cpp`, "linux"), false);
  });

  test("a folder merely NAMED like a platform, outside Platform/, is not skipped", () => {
    assert.strictEqual(isOtherPlatformPath("D:/Src/Code/Framework/Linux/X.cpp", "win32"), false);
  });

  test("an unknown host platform excludes nothing", () => {
    assert.strictEqual(isOtherPlatformPath(`${F}/Platform/Linux/X.cpp`, "darwin"), false);
  });
});
